### ISSUE TITLE
Add validator for java

### ISSUE THREAD

**Issue by kwpeters** [mohlsen/check-engine#14]
An example of how to get the Java version:

```
$ javac -version
javac 1.8.0_31
```

**Comment by YashdalfTheGray** [comment]
This is kind of weird, if you run

``` javascript
require('child_process').exec('java -version', (e, stdout, stderr) => console.log(e, stdout, stderr));
```

you get

```
null '' 'javac 1.8.0_74\n'
```

as the result. Which makes it seem like the java version is printed out through `stderr`. Going to investigate more.

**Edit**: replacing the command string above with `javac -version 2>&1` puts the version in `stdout` instead of `stderr` so yes, the `javac -version` command puts the version out to `stderr`.
